#!/bin/bash
# bash - усовершенствованная и модернизированная вариация командной оболочки Bourne shell.

# Коротко об используемых утилитах:
#
# make - GNU инструмент, который управляет генерацией исполняемых файлов и файлов 
# программы из исходных файлов программы.
#
# echo - unix-утилита, выводящая строку текста в терминал.
#
# sleep - unix-утилита, выполняющая задержку на указанное время.
#
# insmod - устанавливает загружаемый модуль в запущенном ядре.
#
# lsmod - программа для отображения статуса модулей в ядре Linux.
#
# dmesg - выводит сообщения ядра при начальной загрузке Linux или настраивает их буфер.
#
# read - bash-команда для чтения в переменную или из stdin.
#
# rmmod - удаляет загружаемый модуль ядра в запущенном ядре.
#
# tail - показывает последние строки в файле.
#
# grep - поиск в файле по шаблону.
#
# Для получения мануала ввести в терминал man <команда>


# Соберем модули ядра 
make
echo ">>>>> Loading md1.ko..."
echo
sleep 0.8

# Загрузим модули ядра 
insmod md1.ko
echo ">>>>> Loading md2.ko..."
echo
sleep 0.8
insmod md2.ko
echo ">>>>> Modules 1 and 2 was loaded. Let's look at them: "

# Выведем список загружен модулей ядра, чье название содержит строку «md» 
lsmod | grep md
echo
sleep 1

# Посмотрим последние 15 сообщений, выведенных модулями ядра
echo ">>>>> This is the last 15 lines in the system log: "
dmesg | tail -15
echo
read -n 1 -s -r -p "Press any key to continue..."
echo

# Выгрузим 2ой модуль ядра 
echo ">>>>> Remove md2..."
rmmod md2
echo
sleep 0.8

# Загрузим 3ий модуль ядра, возвращающий ошибку
echo ">>>>> Loading md3.ko..."
echo
insmod md3.ko
sleep 0.8

# Посмотрим последние 15 сообщений, выведенных модулями ядра
echo ">>>>> This is the last 15 lines in the system log: "
dmesg | tail -15
echo
read -n 1 -s -r -p "Press any key to continue..."
echo

# Выгрузим 3ий и 1ый модули ядра 
echo ">>>>> Remove md3..."
rmmod md3
echo
sleep 0.8
echo ">>>>> Remove md1..."
rmmod md1
echo
sleep 0.8

# Посмотрим последние 5 сообщений, выведенных модулями ядра
dmesg | tail -5
